### ISSUE TITLE
Add visual tests

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#10]
For both themes

**Comment by web-padawan** [comment]
Dumb visual tests are added, and confirmed to pass on #13

**Comment by web-padawan** [comment]
Moved back to the backlog, let's not create another ticket for actual tests and reuse this one later.

**Comment by web-padawan** [comment]
Actual tests added together with theme change in #17 

For MVP we agreed that both Lumo and Material can look the same, so I consider this done.
