### ISSUE TITLE
Getting error when using in lit-element

### ISSUE THREAD

**Issue by dflorey** [vaadin/vaadin-rich-text-editor#101]
Using the rich text editor in a lit-element throws an error. 
Lit-element render code:

```
render() {
  return html`<vaadin-rich-text-editor></vaadin-text-area>`;
}

```

Stack trace:

```
vaadin-rich-text-editor.js:446 Uncaught TypeError: Cannot read property 'imports' of undefined
    at HTMLElement._prepareToolbar (vaadin-rich-text-editor.js:446)
    at HTMLElement.ready (vaadin-rich-text-editor.js:388)
    at HTMLElement._enableProperties (properties-changed.js:331)
    at HTMLElement.connectedCallback (properties-mixin.js:208)
    at HTMLElement.connectedCallback (element-mixin.js:600)
    at Function.render (shady-render.js:230)
    at HTMLElement.update (lit-element.js:32)
    at HTMLElement._validate (updating-element.js:389)
    at HTMLElement._invalidate (updating-element.js:371)
```

**Comment by heruan** [comment]
You're closing with the wrong tag:

```html
<vaadin-rich-text-editor></vaadin-text-area>
```

**Comment by web-padawan** [comment]
Confirmed it works here: https://broken-cabbage.glitch.me/
Thanks @heruan for the help! 🙂 

Note: when using `webpack` the similar error can happen because of `window.Quill` not exposed globally, in that case consider using following workaround:

1. `npm install expose-loader --save-dev`
2. add these lines to webpack config:
```
module: {
  rules: [
  ...
  {
    test: require.resolve('@vaadin/vaadin-rich-text-editor/vendor/vaadin-quill.js'),
    use: [{
      loader: 'expose-loader',
      options: 'Quill'
    }]
  }
```

**Comment by dflorey** [comment]
Indeed :-)
Closing the tag correctly does not make a difference - it throws the same error.

**Comment by web-padawan** [comment]
@dflorey I have added the comment about what is most likely causing it.
If you are not using webpack and experience same error with Polymer CLI, we will reopen issue.

**Comment by dflorey** [comment]
Hurray! Adding the expose-loader fixed the issue for me.
Thanks a million!
