### ISSUE TITLE
How to set content with given HTML?

### ISSUE THREAD

**Issue by dflorey** [vaadin/vaadin-rich-text-editor#103]
Question: Is there a way to set the contents of the rich text editor from a given HTML string (that may have been retrieved from the editor before)?

**Comment by web-padawan** [comment]
Thanks for the issue. Value should be retrieved and stored preferably in the Delta format (which `value`property is using). Note that `htmlValue` is read-only for security reasons.

**Comment by heruan** [comment]
@dflorey You can convert HTML to Delta using e.g. [node-quill-converter](https://www.npmjs.com/package/node-quill-converter) and then setting the result in the editor.

**Comment by web-padawan** [comment]
The `dangerouslySetHtmlValue` API has been implemented in #119 and released in 1.1.0.
