### ISSUE TITLE
Hidden toolbar/read-only editor

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-rich-text-editor#105]
Like other Vaadin's input elements, a `readonly` switch would be useful to display the rendered content without being able to edit it; this is different from `disabled`, as the latter implies also that the value shouldn't be considered.

A `readonly` editor might also hide the toolbar, to show only the rendered content.

This will also provide a way to just display a previously stored Delta value as HTML, see https://github.com/vaadin/vaadin-rich-text-editor-flow/issues/24.

**Comment by web-padawan** [comment]
This is actually supported, we have just removed the demo for it, see #69 and #82 
Should we return that demo back and improve it somehow? 🤔

**Comment by heruan** [comment]
Well, it seems like it already has this functionality 🤦‍♂️

**Comment by heruan** [comment]
@web-padawan I've just discovered this! Yeah a demo would be useful 😄 

Also, I think a `readonly` editor shouldn't have any height set, but just have its content height; what do you think?
