### ISSUE TITLE
Auto grow is broken when using Lumo compact preset

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-rich-text-editor#106]
Similarly to `vaadin-text-area`, it would be nice to have the editor's height to auto-grow with content.

**Comment by yuriy-fix** [comment]
Dear @heruan ,
We have already implemented this feature over here: https://github.com/vaadin/vaadin-rich-text-editor/pull/88 .
Have you faced any issues using it?

**Comment by heruan** [comment]
I apologize for missing this too (second time today I open a request for an already existing feature 🤦‍♂️)!

The issue I'm facing is basically I cannot get it to work: the editor has a fixed `height: calc(var(--lumo-size-m) * 8)` and it doesn't grow nor shrink while typing. Am I missing something obvious? Any property to be set? The editor is inside a `vaadin-dialog`, if that matters.

Seems today is not my day, better be explicit 🙏

**Comment by yuriy-fix** [comment]
No problem! :)
I have created a small glitch example that could help you with your goal: https://rte-in-dialog.glitch.me
For your case I guess the solution would be to set `min-height` on `vaadin-rich-text-editor`.

**Comment by heruan** [comment]
Thank you @yuriy-fix! Thanks to your glitch I've found the culprit: somehow autogrow stops working when setting `theme="compact"` (which I'm using); seems like the theme style takes precedence and locks the editor height. Is this by design?

**Comment by web-padawan** [comment]
The compact theme is not supposed to break anything, it just changes the values of CSS custom properties and generally it seems to work for me: 
https://glitch.com/edit/#!/brindle-cake?path=index.html:5:0

**Comment by heruan** [comment]
In your glitch you don't set `theme="compact"`, but if you do (see https://glitch.com/edit/amused-saver) the editor does not adjust its height anymore.

**Comment by yuriy-fix** [comment]
Thanks, @heruan!
Good catch! We will try to fix it asap :)
