### ISSUE TITLE
Can't get focus on typing area when in a dialog

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-rich-text-editor#125]
When the editor is inside a dialog, you can't reach the typing area with the <kbd>TAB</kbd> key.

Glitch: https://glitch.com/edit/#!/bristle-gorgonzola
Steps:
1. open the dialog;
2. type something on the text-field;
3. press <kbd>TAB</kbd> to start typing in the editor;
4. you won't 🙁 

Remotely related to #117

**Comment by yuriy-fix** [comment]
Closed via https://github.com/vaadin/vaadin-overlay/pull/163
