### ISSUE TITLE
Toolbar buttons not clickable on Safari

### ISSUE THREAD

**Issue by TGit911iger** [vaadin/vaadin-rich-text-editor#130]
Hello!

I am using Rich Text Editor with Vaadin 15.0.2 and Vaadin 14.1.20.

There is a problem with Safari, with Chrome there are no problems.

Of course I tried this with your sample: https://demo.vaadin.com/invoice-editor-app/

It is not working, too.

Here is the problem:

In your sample I am selecting the text "hotel" and pressing the bold button. Under Safari the caret jumps to the beginning of the text when pressing the bold button. Under Chrome "hotel" is marked bold - ok.

There may be a problem with "window.getSelection" under Safari.

System is mac.png.

Thank you very much for your help, Thomas
<img width="279" alt="mac" src="https://user-images.githubusercontent.com/9194576/77413860-5b3b9000-6dc0-11ea-8618-16f61e7373db.png">
<img width="987" alt="editor" src="https://user-images.githubusercontent.com/9194576/77413864-5bd42680-6dc0-11ea-9377-5997b9efd967.png">

**Comment by web-padawan** [comment]
Thanks for the issue. Confirmed using Safari 13.0.5. 

Can be also reproduced with [1.0.0 demos](https://cdn.vaadin.com/vaadin-rich-text-editor/1.0.0/demo/), so not a regression of web component.

We are using `getSelection` polyfill, but unfortunately it has some edge cases. One possible solution could be to test if the newer polyfill version helps, as reported in #129

**Comment by omair100** [comment]
Hi

Is there any progress on this issue - as our users are experiencing the same issue in safari.

Best Regards

**Comment by PaulQDC** [comment]
Why has this issue been closed ?  Still happening on latest OS and Vaadin version 14.3.0.  If was closed with a fix, what is the fix?  This is NOT a minor issue or inconvenience for us.  It is a SHOW STOPPER.

**Comment by web-padawan** [comment]
@PaulQDC this is closed because the fix was merged and released. Please upgrade to Vaadin 14.3.9 or 14.4.0.
