### ISSUE TITLE
Undo and redo buttons in RTL mode should be flipped horizontally

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-rich-text-editor#133]
At the moment, in RTL mode, undo and redo buttons look like this:
![image](https://user-images.githubusercontent.com/32511762/79751172-d0947500-831a-11ea-83a7-1980546b33ab.png)

I expect them to look like the following:
![image](https://user-images.githubusercontent.com/32511762/79752458-00dd1300-831d-11ea-9e93-e7297599ac96.png)

**Comment by yuriy-fix** [comment]
@mehdi-vaadin , So what should be the button responsible for undo?
1. pointing left
2. pointing right

**Comment by mehdi-vaadin** [comment]
The first button (in RTL direction), which points to the right, should be the undo button.
