### ISSUE TITLE
Change artifacts namings

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-rich-text-editor#162]
Change naming of the artifacts:
- `<artifactId>vaadin-rich-text-editor-flow-root</artifactId>` -> `<artifactId>vaadin-rich-text-editor-flow-parent</artifactId>` (**-root** -> **-parent**; `pom.xml`)
- ` <artifactId>vaadin-rich-text-editor-flow-vaadincom-demo</artifactId>` -> ` <artifactId>vaadin-rich-text-editor-flow-demo</artifactId>` (remove **vaadincom**; `demo/pom.xml`)
- rename the demo folder as well

**Comment by web-padawan** [comment]
Done in the monorepo, see https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-rich-text-editor-flow-parent/pom.xml
