### ISSUE TITLE
Rich Text Editor does not behave correctly in SAFARI on the desktop OR iPad

### ISSUE THREAD

**Issue by PaulQDC** [vaadin/vaadin-rich-text-editor#166]
when accessing the RTE From Safari (14) on the desktop and on the iPad any click of the icons (bold, underline, etc) jumps the cursor back to the start of the editor.  There is no way to annotate existing text or annotate as you go.

We are using Vaadin version 14.3.0

**Comment by PaulQDC** [comment]
Apparently fixed in 14.3.9 and 14.4.0.  would be nice if that was noted in the previous open issues.

**Comment by web-padawan** [comment]
The fix was released at [14.3.2](https://github.com/vaadin/platform/releases/tag/14.3.2) but not mentioned in the release notes by mistake. 
Thanks for reporting and sorry for the inconvenience.
