### ISSUE TITLE
Editor mark and list problem

### ISSUE THREAD

**Issue by musacavus** [vaadin/vaadin-rich-text-editor#167]
- I am entering 3 articles
- I mark as item

problem: although I marked it as an item, it perceives as a list

![unnamed](https://user-images.githubusercontent.com/3061919/96004237-d3909e00-0e43-11eb-8b3b-7dbfb5a19117.png)

**Comment by web-padawan** [comment]
Thanks for the issue. The screenshot shows Quill and not a `vaadin-rich-text-editor` component.

Can you reproduce the bug with our live demos? https://cdn.vaadin.com/vaadin-rich-text-editor/1.3.0/demo/
Also, what do you mean by "mark as item"? Please describe which buttons you click and in which order.

**Comment by tomivirkki** [comment]
Closing as inactive, please let us know if this is still relevant
