### ISSUE TITLE
Setting initial value with asHtml().setValue() does not trigger value change event

### ISSUE THREAD

**Issue by tltv** [vaadin/vaadin-rich-text-editor#175]
With Flow integration for vaadin-rich-text-editor. Constructing new instance with `new RichTextEditor()` and then setting initial value with `asHtml().setValue("abc")` does not trigger value change event as expected. 
For comparison, value change event is triggered when setting initial value just with `setValue("abc")`.

Sample code to reproduce issue:
```
@Route(value = "test")
public class TestView extends HorizontalLayout {

    public TestView() {
    	RichTextEditor rte = new RichTextEditor();
        add(rte);
        rte.addValueChangeListener(e -> {
            // Expected to be run when navigating to '/test' view but its not.
            Notification.show(rte.getValue());
        });
        rte.asHtml().setValue("<h1>Test</h1>");
    }

}
```

I suspect that main issue here is that underlying web component's `value` property is not kept synchronized with the given html. Workaround that may help a bit is to set `value` property by force for example with `setPresentationValue("<h1>Test</h1>")` right after calling `asHtml().setValue`. This might how ever cause bad side effects in other use cases.

Tested with Vaadin version 14.4.5.

**Comment by ZheSun88** [comment]
released with platform 19.0.3
