### ISSUE TITLE
Caret should be placed on the new line (Safari)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#34]
Pressing Enter bolded or otherwise formatted text moves the caret to the end of the line, not to a new line (a new line is created still)

This occurs on Safari only, works at https://quilljs.com/playground/ though

**Comment by web-padawan** [comment]
As a workaround we could disable the caching which polyfill does:
https://github.com/GoogleChromeLabs/shadow-selection-polyfill/blob/fdceaecb8c56e03932f2178030b36efe9f763082/shadow.js#L278

It seems to solve the problem although the performance impact needs to be verified.
