### ISSUE TITLE
Simplify the default styles

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#37]
Comments:
- Nit: why the 2px padding in the toolbar buttons?
- Nit: why no margin-bottom for the toolbar buttons?
- Nit: would not reduce the opacity of the toolbar buttons in the core styles
- Nit: would let the font-family and font-size inherit from the parent (just like line-height and color currently are)
- Nit: would use a border around the host instead of the toolbar and the content (easier to remove if needed), and a light background-color for the toolbar
- Nit: would avoid all pixel units in the core content/editor styles and use em instead

**Comment by tomivirkki** [comment]
Related #29

**Comment by web-padawan** [comment]
> Nit: why the 2px padding in the toolbar buttons?

The `<button>` element has some default padding which we need to reset:

![screen shot 2018-10-15 at 15 19 58](https://user-images.githubusercontent.com/10589913/46950600-d35f3b80-d08d-11e8-8c44-8a8c4933c404.png)
