### ISSUE TITLE
Sanitize pasted content

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#5]
- Formatting shouldn't break when pasting arbitrarily styled content into the editor.
- Pasted content is cleaned up from all formatting – only text content is preserved
- Copying from another vaadin-rich-text-editor should still retain formatting
- Test that the pasted content gets sanitized

**Comment by web-padawan** [comment]
Checklist to verify: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Tests

**Comment by tomivirkki** [comment]
Works fine. Didn't find any issues when pasting content.
