### ISSUE TITLE
Reconsider toolbar button styling part names

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-rich-text-editor#59]
Instead of `part="foobar-button"`, consider using `part="foobar button"`.

This should make it more future-proof if browsers eventually start supporting the `::part` pseudo-element selector, as you could still target `::part(button)`, which would not be possible if we use `part="foobar-button"`.

The change should have minimal effect on current users, as they will in any case need to learn about the more complex attribute selectors if they want to target all of the toolbar buttons with a single selector, i.e. `[part$="button"]` vs `[part~="button"]`.

**Comment by jouni** [comment]
Continuing with this train-of-thought, should it actually be `part="toolbar-button"`? I feel it might be awkward to write `vaadin-rich-text-editor::part(button)` vs `vaadin-rich-text-editor::part(toolbar-button)`.

**Comment by jouni** [comment]
Then, does it seem logical to write `vaadin-rich-text-editor::part(bold)`? I think it’s not too bad at least. Or should it still be `vaadin-rich-text-editor::part(bold-button)`?

I feel lost now 😅

**Comment by tomivirkki** [comment]
:) So should it be `<... part="toolbar-button bold-button">` then? Effectively, we would add "toolbar-button" to all the current buttons. That said, maybe the current `part="group"` should be `part="toolbar-group"`?

**Comment by YuriyVaadin** [comment]
One more thing to consider in the scope of this ticket:
we can update styling docs to include mentioning about the possible way to select all buttons.

**Comment by web-padawan** [comment]
@jouni so what's the final decision regarding this ticket?

Both `toolbar-group` and `toolbar-button` make sense for me.
We don't have 2 different words used for the same part attribute value anywhere though.

How about e.g. `toolbar-button-bold`? It's a bit long but self descriptive.

**Comment by tomivirkki** [comment]
`toolbar-button-bold` would't probably work with `::part` if you need to target all buttons somehow

**Comment by web-padawan** [comment]
Ok, so should we add both, e.g. `toolbar-button toolbar-button-bold`?
Somehow similar to what BEM does. I don't really like it but it would be more consistent.

**Comment by jouni** [comment]
I suppose you can’t combine multiple pseudo-element selectors like this `::part(toolbar-button)::part(bold)` (assuming there was `<button part="toolbar-button bold">`)…
