### ISSUE TITLE
Focusing the toolbar is inconsistent

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-rich-text-editor#67]
Moving focus back to the toolbar when creating lists is not consistent (unable to use Shift + Tab when cursor is on the empty list item with no text)

**Comment by web-padawan** [comment]
Update: appears to be shadow selection polyfill issue.

Working:
- focus the editor
- type something from keyboard
- press Shift + Tab

Broken:
- focus the editor
- type something from keyboard
- click anywhere in the editor
- press Shift + Tab

**Comment by web-padawan** [comment]
Still reproducible, now the broken sequence (in the empty editor) is:

1. apply bold formatting
2. apply list
3. type some  characters
4. press <kbd>Shift</kbd> + <kbd>Tab</kbd>
5. see the blinking outline around the toolbar button

Apparently focus moves, but then is moved back immediately.
