### ISSUE TITLE
Get rid of readonly demo

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-rich-text-editor#69]

**Comment by jouni** [comment]
What was the reasoning for getting rid of it? I think it’s useful at the moment so that there’s an easy way to render the Quill Delta format to HTML.

**Comment by YuriyVaadin** [comment]
It was more like a point to consider as dx/ux tests participants were not able to recognise `readonly rich-text-editor` as `rich-text-editor`

**Comment by jouni** [comment]
As discussed face-to-face, `readonly` is probably unnecessary, as you can get the `htmlValue` out of the component as well, if you need to render it (although that requires a bit of work).

**Comment by tomivirkki** [comment]
Discussed with Jouni,  let's keep the API, but drop the readonly demo
