### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#7]
- Extend themable mixin
- Add necessary parts
- Make sure the theme colors affect the editor parts properly

**Comment by web-padawan** [comment]
We should consider the following improvements:
- getting rid of `quill.js` and using `quill-core.js` instead (saves  > 100 KB)
- having icon sets for all the buttons needed (both Lumo and Material)
- using our own CSS instead of the built-in "snow" theme

**Comment by web-padawan** [comment]
For the icons, we could use following from Material set:

- `format_bold`
- `format_italic`
- `format_underlined
- `format_strikethrough`
- `format_list_numbered`
- `format_list_bulleted`
- `format_quote`
- `format_align_center`
- `format_align_left`
- `format_align_right`
- `format_align_justify`
- `code`

Missing icons:
- h1
- h2
- sub-script
- super-script
