### ISSUE TITLE
Add hyperlink toolbar button

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-rich-text-editor#70]

**Comment by web-padawan** [comment]
@jouni is the Material `link` icon good enough for both Lumo and Material?
https://material.io/tools/icons/?search=link&icon=link&style=baseline

If so, we could add it to the RTE icons. Otherwise, another Lumo update would be needed.

**Comment by jouni** [comment]
Use that for now. We can update that after 1.0 even (I’ll probably want to use another icon for Lumo).
