### ISSUE TITLE
Unexpected list behaviour on Safari

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#81]
![safari-list](https://user-images.githubusercontent.com/1222264/47637621-fd702d80-db64-11e8-8168-1f5e5a7d6720.gif)

**Comment by web-padawan** [comment]
The following error can be observed in the console:
```
IndexSizeError: The index is not in the allowed range.
```

Caused by this line: https://github.com/quilljs/quill/blob/1.3.6/core/editor.js#L161

Investigating why it only happens starting from the second time Enter is pressed...

**Comment by web-padawan** [comment]
Going deeper into the Quill internals, documenting the steps:

1. the newline is being inserted:
https://github.com/quilljs/parchment/blob/master/src/blot/abstract/shadow.ts#L115

2. `optimize` method called:
https://github.com/quilljs/quill/blob/1.3.6/blots/scroll.js#L77

3. `scroll-optimize` event is dispatched:
https://github.com/quilljs/quill/blob/1.3.6/blots/scroll.js#L140

Have not yet found the exact line where error happens.
