### ISSUE TITLE
Firefox selection and focus is broken

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-rich-text-editor#90]
Whenever moving the focus to the toolbar with <kbd>Shift</kbd> + <kbd>Tab</kbd> on Firefox selection mechanism is broken right after that: the focus goes to the editor container and you cannot place the caret where you need it in the content.

Demo using the keyboard <kbd>arrows</kbd> and <kbd>Shift</kbd>, <kbd>Tab</kbd> buttons:

![ff-bug](https://user-images.githubusercontent.com/29372419/48055340-08a40880-e1b8-11e8-8545-d4d1d453f68e.gif)

**Comment by web-padawan** [comment]
Appears to be Firefox issue related to how `contenteditable` works in Shadow DOM:
https://jsfiddle.net/webpadawan/g6vku9L3/

Will submit an issue to the `bugzilla`, in the meanwhile trying to workaround it.
